import numpy as np



# Background: The Lanczos Iteration is an algorithm used to approximate the eigenvalues and eigenvectors of a large symmetric matrix. 
# It is particularly useful for sparse matrices. The process generates an orthonormal basis for the Krylov subspace, which is a sequence 
# of vector spaces generated by the initial vector b and the matrix A. The algorithm iteratively constructs a tridiagonal matrix T 
# whose eigenvalues approximate those of A. The orthonormal basis vectors are stored in the matrix Q. The algorithm involves three main 
# steps: initializing the first vector, iteratively computing the next vector in the sequence, and orthogonalizing it against the 
# previous vectors to ensure orthonormality.


def lanczos(A, b, m):
    '''Inputs:
    A : Matrix, 2d array of arbitrary size M * M
    b : Vector, 1d array of arbitrary size M * 1
    m : integer, m < M
    Outputs:
    Q : Matrix, 2d array of size M*(m+1)
    '''
    M = A.shape[0]
    Q = np.zeros((M, m+1))
    q = b / np.linalg.norm(b)
    Q[:, 0] = q
    beta = 0
    for j in range(m):
        v = A @ q
        if j > 0:
            v -= beta * Q[:, j-1]
        alpha = np.dot(q, v)
        v -= alpha * q
        beta = np.linalg.norm(v)
        if beta < 1e-10:
            break
        q = v / beta
        Q[:, j+1] = q
    return Q

from scicode.parse.parse import process_hdf5_to_tuple
targets = process_hdf5_to_tuple('5.1', 3)
target = targets[0]

n = 7
h = 1.0/n
diagonal = [2/h for i in range(n)]
diagonal_up = [-1/h for i in range(n-1)]
diagonal_down = [-1/h for i in range(n-1)]
A = np.diag(diagonal) + np.diag(diagonal_up, 1) + np.diag(diagonal_down, -1)
b = np.array([0.1,0.1,0.0,0.1,0.0,0.1,0.1])
m = 5
assert np.allclose(lanczos(A,b,m), target)
target = targets[1]

n = 7
h = 1.0/n
diagonal = [1/h for i in range(n)]
diagonal_up = [-0.9/h for i in range(n-1)]
diagonal_down = [-0.9/h for i in range(n-1)]
A = np.diag(diagonal) + np.diag(diagonal_up, 1) + np.diag(diagonal_down, -1)
b = np.array([0.1,10.1,0.0,0.5,0.2,0.3,0.5])
m = 5
assert np.allclose(lanczos(A,b,m), target)
target = targets[2]

n = 7
h = 1.0/n
diagonal = [1/h for i in range(n)]
diagonal_up = [-9/h for i in range(n-1)]
diagonal_down = [-9/h for i in range(n-1)]
A = np.diag(diagonal) + np.diag(diagonal_up, 1) + np.diag(diagonal_down, -1)
A[:, 0] = 0
A[0, :] = 0
A[0, 0] = 1/h
b = np.array([0.1,0.1,0.0,10,0.0,0.1,0.1])
m = 4
assert np.allclose(lanczos(A,b,m), target)
