import numpy as np



# Background: The Lanczos iteration is an algorithm used to approximate the eigenvalues and eigenvectors of a large symmetric matrix. 
# It constructs an orthonormal basis for the Krylov subspace, which is a sequence of vector spaces generated by the powers of a matrix 
# applied to an initial vector. In each iteration, the algorithm generates a new orthogonal vector and stores these in a matrix Q. 
# The columns of Q form an orthonormal basis for the Krylov subspace. The process involves orthogonalizing the new vector against the 
# previously computed vectors to maintain orthogonality, typically using the Gram-Schmidt process.


def lanczos(A, b, m):
    '''Inputs:
    A : Matrix, 2d array of arbitrary size M * M
    b : Vector, 1d array of arbitrary size M * 1
    m : integer, m < M
    Outputs:
    Q : Matrix, 2d array of size M*(m+1)
    '''
    M = A.shape[0]
    Q = np.zeros((M, m + 1))
    q = b / np.linalg.norm(b)
    Q[:, 0] = q
    beta = 0

    for j in range(m):
        v = A @ Q[:, j] - beta * Q[:, j - 1] if j > 0 else A @ Q[:, j]
        alpha = np.dot(Q[:, j], v)
        v = v - alpha * Q[:, j]
        
        if j > 0:
            v = v - beta * Q[:, j - 1]
        
        beta = np.linalg.norm(v)
        
        if beta < 1e-10:
            break
        
        Q[:, j + 1] = v / beta

    return Q

from scicode.parse.parse import process_hdf5_to_tuple
targets = process_hdf5_to_tuple('5.1', 3)
target = targets[0]

n = 7
h = 1.0/n
diagonal = [2/h for i in range(n)]
diagonal_up = [-1/h for i in range(n-1)]
diagonal_down = [-1/h for i in range(n-1)]
A = np.diag(diagonal) + np.diag(diagonal_up, 1) + np.diag(diagonal_down, -1)
b = np.array([0.1,0.1,0.0,0.1,0.0,0.1,0.1])
m = 5
assert np.allclose(lanczos(A,b,m), target)
target = targets[1]

n = 7
h = 1.0/n
diagonal = [1/h for i in range(n)]
diagonal_up = [-0.9/h for i in range(n-1)]
diagonal_down = [-0.9/h for i in range(n-1)]
A = np.diag(diagonal) + np.diag(diagonal_up, 1) + np.diag(diagonal_down, -1)
b = np.array([0.1,10.1,0.0,0.5,0.2,0.3,0.5])
m = 5
assert np.allclose(lanczos(A,b,m), target)
target = targets[2]

n = 7
h = 1.0/n
diagonal = [1/h for i in range(n)]
diagonal_up = [-9/h for i in range(n-1)]
diagonal_down = [-9/h for i in range(n-1)]
A = np.diag(diagonal) + np.diag(diagonal_up, 1) + np.diag(diagonal_down, -1)
A[:, 0] = 0
A[0, :] = 0
A[0, 0] = 1/h
b = np.array([0.1,0.1,0.0,10,0.0,0.1,0.1])
m = 4
assert np.allclose(lanczos(A,b,m), target)
